jobs:
  build-all:
    name: Compile (no tests) with JDK 11
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      uses: actions/cache@v1
      with:
        key: m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: 'm2-

          '
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "jboss", "name": "JBoss", "url": "https://repository.jboss.org/nexus/content/groups/public"
          }]'
    - continue-on-error: true
      name: Print Version
      run: mvn -v
    - continue-on-error: true
      name: Build
      run: mvn -U -B -fae -DskipTests -Dfindbugs clean install
    - continue-on-error: true
      name: Tar Maven Repo
      run: tar -czf maven-repo.tgz -C ~ .m2/repository
      shell: bash
    - continue-on-error: true
      name: Persist Maven Repo
      uses: actions/upload-artifact@v1
      with:
        name: maven-repo
        path: maven-repo.tgz
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: surefire-reports-build
        path: '**/surefire*-reports/*.txt

          **/*.dump*

          '
  test-matrix:
    name: JDK ${{ matrix.jdk }} - ${{ matrix.module }} - ${{ matrix.os }}
    needs: build-all
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: matrix.os == 'ubuntu-latest'
      name: Update hosts - linux
      run: 'cat /etc/hosts

        sudo bash -c "echo ''127.0.0.1   localhost localhost.localdomain localhost4
        localhost4.localdomain4'' > /etc/hosts"

        sudo bash -c "echo ''::1         localhost localhost.localdomain localhost6
        localhost6.localdomain6'' >> /etc/hosts"

        sudo sysctl -w fs.file-max=2097152

        '
    - continue-on-error: true
      if: matrix.os == 'windows-latest'
      name: Update hosts - windows
      run: "type %SystemRoot%\\System32\\drivers\\etc\\hosts\necho '127.0.0.1   localhost\
        \ localhost.localdomain localhost4 localhost4.localdomain4' >\t%SystemRoot%\\\
        System32\\drivers\\etc\\hosts\necho '::1         localhost localhost.localdomain\
        \ localhost6 localhost6.localdomain6' >> %SystemRoot%\\System32\\drivers\\\
        etc\\hosts\n"
      shell: cmd
    - continue-on-error: true
      uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Host information
      run: 'hostname || true

        '
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Download Maven Repo
      uses: actions/download-artifact@v1
      with:
        name: maven-repo
        path: .
    - continue-on-error: true
      name: Extract Maven Repo
      run: tar -xzf maven-repo.tgz -C ~
      shell: bash
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: ${{ matrix.openjdk_impl }}
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "jboss", "name": "JBoss", "url": "https://repository.jboss.org/nexus/content/groups/public"
          }]'
    - continue-on-error: true
      name: Print Version
      run: mvn -v
    - continue-on-error: true
      name: Run Tests
      run: mvn -U -B -fae test -Pproxy '-DfailIfNoTests=false' -pl ${{ matrix.module
        }}
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: surefire-reports-${{ matrix.jdk }}-${{ matrix.module }}-${{ matrix.os
          }}
        path: '**/surefire*-reports/*.txt

          **/*.dump*

          '
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - 11
        - 17
        - 21
        module:
        - core
        - servlet
        - websockets-jsr
        openjdk_impl:
        - temurin
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
  test-matrix-ipv6:
    name: JDK ${{ matrix.jdk }} - ipv6 - ${{ matrix.module }} ${{ matrix.proxy }}
      - ${{ matrix.os }}
    needs: build-all
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: matrix.os == 'ubuntu-latest'
      name: Update hosts - linux
      run: 'sudo bash -c "echo ''127.0.0.1   localhost localhost.localdomain localhost4
        localhost4.localdomain4'' > /etc/hosts"

        sudo bash -c "echo ''::1         localhost localhost.localdomain localhost6
        localhost6.localdomain6'' >> /etc/hosts"

        sudo sysctl -w fs.file-max=2097152

        '
    - continue-on-error: true
      uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Host information
      run: 'hostname || true

        '
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Download Maven Repo
      uses: actions/download-artifact@v1
      with:
        name: maven-repo
        path: .
    - continue-on-error: true
      name: Extract Maven Repo
      run: tar -xzf maven-repo.tgz -C ~
      shell: bash
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "jboss", "name": "JBoss", "url": "https://repository.jboss.org/nexus/content/groups/public"
          }]'
    - continue-on-error: true
      name: Print Version
      run: mvn -v
    - continue-on-error: true
      name: Run Tests
      run: mvn -U -B -fae test ${{ matrix.proxy }} '-DfailIfNoTests=false' -pl ${{
        matrix.module }} -Dtest.ipv6=true
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: surefire-reports-${{ matrix.jdk }}-ipv6-${{ matrix.module }}${{ matrix.proxy
          }}-${{ matrix.os }}
        path: '**/surefire*-reports/*.txt

          **/*.dump*

          '
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - 11
        module:
        - core
        - servlet
        - websockets-jsr
        os:
        - ubuntu-latest
        proxy:
        - -Pproxy
        - ''
name: Undertow CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
